// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPpcO960nzqM5Bu-UAOxZ2kPG7u4zolbw',
    appId: '1:843999077594:web:041b20dd25d032986eb1e3',
    messagingSenderId: '843999077594',
    projectId: 'test-firebase-flutter-89db3',
    authDomain: 'test-firebase-flutter-89db3.firebaseapp.com',
    storageBucket: 'test-firebase-flutter-89db3.firebasestorage.app',
    measurementId: 'G-MBRY5DMXTT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR4dJJKn91HOFkBJymY9vejIIIauApwFQ',
    appId: '1:843999077594:android:25f99f1993611a946eb1e3',
    messagingSenderId: '843999077594',
    projectId: 'test-firebase-flutter-89db3',
    storageBucket: 'test-firebase-flutter-89db3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ_kkylH6Qdip7IvWaDhBowYk1mCobk-Q',
    appId: '1:843999077594:ios:98544ad1e5f87c016eb1e3',
    messagingSenderId: '843999077594',
    projectId: 'test-firebase-flutter-89db3',
    storageBucket: 'test-firebase-flutter-89db3.firebasestorage.app',
    iosBundleId: 'com.example.appdev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ_kkylH6Qdip7IvWaDhBowYk1mCobk-Q',
    appId: '1:843999077594:ios:98544ad1e5f87c016eb1e3',
    messagingSenderId: '843999077594',
    projectId: 'test-firebase-flutter-89db3',
    storageBucket: 'test-firebase-flutter-89db3.firebasestorage.app',
    iosBundleId: 'com.example.appdev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPpcO960nzqM5Bu-UAOxZ2kPG7u4zolbw',
    appId: '1:843999077594:web:d0d291029d6146b76eb1e3',
    messagingSenderId: '843999077594',
    projectId: 'test-firebase-flutter-89db3',
    authDomain: 'test-firebase-flutter-89db3.firebaseapp.com',
    storageBucket: 'test-firebase-flutter-89db3.firebasestorage.app',
    measurementId: 'G-5CK8ZZQH7J',
  );
}
